# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"B\n\x0b\x43hatRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0e\n\x06prompt\x18\x03 \x01(\t\"=\n\x0c\x43hatResponse\x12\r\n\x05\x63hunk\x18\x01 \x01(\t\x12\x1e\n\x07receipt\x18\x02 \x01(\x0b\x32\r.chat.Receipt\"j\n\x07Receipt\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x15\n\rresponse_hash\x18\x03 \x01(\t\x12\x11\n\tsignature\x18\x04 \x01(\t\x12\x0e\n\x06key_id\x18\x05 \x01(\t2E\n\x0c\x41gentService\x12\x35\n\nStreamChat\x12\x11.chat.ChatRequest\x1a\x12.chat.ChatResponse0\x01\x42\x12\xaa\x02\x0f\x41gentApp.Protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\017AgentApp.Protos'
  _globals['_CHATREQUEST']._serialized_start=20
  _globals['_CHATREQUEST']._serialized_end=86
  _globals['_CHATRESPONSE']._serialized_start=88
  _globals['_CHATRESPONSE']._serialized_end=149
  _globals['_RECEIPT']._serialized_start=151
  _globals['_RECEIPT']._serialized_end=257
  _globals['_AGENTSERVICE']._serialized_start=259
  _globals['_AGENTSERVICE']._serialized_end=328
# @@protoc_insertion_point(module_scope)
