# app/graph/state.py
from typing import Annotated, Optional, Sequence, List, Dict, Any
from typing_extensions import TypedDict
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages

class AgentState(TypedDict):
    # add_messages automatically appends new messages to the existing sequence
    messages: Annotated[Sequence[BaseMessage], add_messages]
    user_id: Optional[str]
    session_id: Optional[str]
    current_domain: Optional[str]

    # ─── PHASE 2: WORKFLOW MEMORY (PROCEDURAL STATE) ───
    # Keeps track of the execution plan generated by the Planner Node
    tasks: List[Dict[str, Any]]  # Example: [{"id": 1, "desc": "Find paper", "status": "pending"}]
    current_task_id: Optional[int]
    
    # ─── PHASE 2: LOOP MANAGEMENT & SAFEGUARDS ───
    iteration_count: int         # Tracks graph cycles to enforce Max Iterations
    tool_call_count: int         # Tracks total tools invoked to enforce Budget Limits
    action_history: List[str]    # Records hashed tool calls to prevent Duplicate Actions

    # ─── EVALUATION MEMORY ───
    critic_feedback: Optional[str]
    reflection_notes: Optional[str]
    final_answer: Optional[str]